### ISSUE TITLE
Known scheduling issues

### ISSUE THREAD

**Issue by ahoskins** [rosshamish/classtime#101]
Fall 2015;

- [ ] Cmput 466 301 379 ece 322 449 hist 115 (John's software schedule)

**Comment by rosshamish** [comment]
Haha darn, was hoping this would be fixed by #98. Thursday evening is the soonest I can look into this. 
First steps (if someone sees this please feel free to do these and post the results here). 
- manually check if a schedule is actually possible (excel, baby)
- try with 5 instead of 6 courses. 
  - remove a course, try to schedule
  - add it back, remove a different course, try to schedule
  - repeat
- try scheduling each of these courses individually to see if it's an isolated issue with one course "type" failing (like #98 was)
- try scheduling pairs of courses together

**Comment by rosshamish** [comment]
Also an issue:

I've put together this schedule in beartracks, but it doesn't get generated by classtime

![image](https://cloud.githubusercontent.com/assets/1522678/8686084/058eea7e-2a38-11e5-98df-684b0e206e97.png)

![image](https://cloud.githubusercontent.com/assets/1522678/8686116/4a19a47c-2a38-11e5-97ea-7400e1a16cd9.png)

![image](https://cloud.githubusercontent.com/assets/1522678/8686117/4f8d2262-2a38-11e5-87f1-5e888176d93a.png)


Without ECE 449, a single schedule is found, but it's not the same shape as the one I built manually in beartracks

![image](https://cloud.githubusercontent.com/assets/1522678/8686131/63082a62-2a38-11e5-9a07-23dfe45acc2b.png)

**Comment by rosshamish** [comment]
Note: these types of issues will go away with the new sched-gen system in #109
